id: ADDING_TREES
version: 0.5.0
author: PackFromScratch

addons:
  language-yaml: "1.+"
  chunk-generator-noise-3d: "1.+"
  config-noise-function: "1.+"
  palette-block-shortcut: "1.+"
  config-biome: "1.+"
  biome-provider-single: "1.+"

  config-palette: "1.+"

  config-feature: "1.+"
  config-distributors: "1.+"
  config-locators: "1.+"
  structure-block-shortcut: "1.+"
  generation-stage-feature: "1.+"

  structure-terrascript-loader: "1.+"
  structure-sponge-loader: "1.+"

generator: NOISE_3D

biomes:
  type: SINGLE
  biome: FIRST_BIOME

stages:
  - id: trees
    type: FEATURE
  # The trees generation stage will come before flora, making it generate first.
  - id: flora
    type: FEATURE
